version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: php-app-image
    restart: unless-stopped
    working_dir: /app
    tty: true
    ports:
      - 8081:80
    volumes:
      - ./:/app/
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf